version: '3.5'

services:
  api01: &api
    build: .
    hostname: api01
    networks:
      - backend
      - payment-processor    
    expose: 
      - "3000"
    depends_on:
      - db
    labels:
      - "autoheal=true"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api02:
    <<: *api
    hostname: api02
    networks:
      - backend
      - payment-processor    
    expose: 
      - "3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    privileged: true
    environment:
      - AUTOHEAL_INTERVAL=60  
      - AUTOHEAL_START_PERIOD=300 
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10  
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=rinha_2025_db
     - AUTOHEAL_INTERVAL=60  
     - AUTOHEAL_START_PERIOD=300 
     - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10  
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "200MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true