services:
  redis:
    image: redis:7-alpine
    command: redis-server --loglevel debug
    hostname: redis
    ports:
      - "6379:6379"


  db:
    image: postgres:latest
    hostname: db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=rinha_2025_db
     - AUTOHEAL_INTERVAL=60  
     - AUTOHEAL_START_PERIOD=300 
     - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10  
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
